/**
 * Generates `src/generated/stock-theme.ts` — the pregenerated reverse index for
 * Tailwind's stock theme, used by the engine-free (edge-safe) path.
 *
 * Run via `npm run generate` whenever `tailwindcss` is updated. A snapshot test
 * (`stock-theme.test.ts`) asserts the embedded output matches the live engine,
 * so CI fails if this is stale.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'
import { loadDesignSystem } from '../src/design-system.ts'
import { buildReverseIndex, computeMediaVariants } from '../src/reverse-index.ts'
import { CssToTailwind } from '../src/converter.ts'
import type { StockTheme } from '../src/embedded.ts'

const require = createRequire(import.meta.url)
const here = dirname(fileURLToPath(import.meta.url))
const REM = 16

const tailwindVersion: string = require('tailwindcss/package.json').version

const ds = await loadDesignSystem()
const index = buildReverseIndex(ds, REM)

// Live converter, used to find which index entries the matchers already
// reproduce (so we can drop them and keep the embedded data small).
const conv = new CssToTailwind({ css: '@import "tailwindcss";' })
await conv.convert('.x{}')
const liveIndex = (conv as unknown as { index: typeof index }).index
const declCache = (conv as unknown as { declCache: Map<string, string[]> }).declCache

async function classesFor(decl: string): Promise<string> {
  const { nodes } = await conv.convert(`.x{ ${decl} }`)
  return (nodes[0]?.tailwindClasses ?? []).join(' ')
}
const declOf = (key: string) => {
  const i = key.indexOf('|')
  return `${key.slice(0, i)}: ${key.slice(i + 1)}`
}

const entries = [...liveIndex.decls]
const fullOut = new Map<string, string>()
for (const [key] of entries) fullOut.set(key, await classesFor(declOf(key)))

// Drop the exact index -> matcher-only behavior, then keep only entries the
// matchers can't reproduce (statics, irregular functionals, named scales).
liveIndex.decls.clear()
declCache.clear()
const minimal: [string, string][] = []
for (const [key, cls] of entries) {
  if ((await classesFor(declOf(key))) !== fullOut.get(key)) minimal.push([key, cls])
}

// Split into theme-independent decls and token-derived decls (whose CSS is a
// single `prop: var(--token)`), so a custom @theme can recompute the latter.
const TOKEN_VALUE = /^var\((--[\w-]+)\)$/
const plainDecls: Record<string, string> = {}
const tokenDecls: [string, string, string][] = []
for (const [key, cls] of minimal) {
  const css = ds.candidatesToCss([cls])[0] ?? ''
  const m = /\{\s*([^:]+):\s*([^;]+?)\s*;?\s*\}/.exec(css.replace(/\s+/g, ' '))
  const varMatch = m && TOKEN_VALUE.exec(m[2].trim())
  if (m && varMatch) tokenDecls.push([m[1].trim(), varMatch[1], cls])
  else plainDecls[key] = cls
}

const fromMap = <V>(m: Map<string, V>) => Object.fromEntries(m)
// Every non-color theme var (colors live in `palette`); lets a custom @theme
// override radius/spacing/breakpoints/weights/etc. and rebuild the index.
const themeVars = Object.fromEntries([...index.vars].filter(([n]) => !n.startsWith('--color-')))

const data: StockTheme = {
  tailwindVersion,
  themeVars,
  palette: fromMap(index.palette),
  plainDecls,
  tokenDecls,
  propToRoot: fromMap(index.propToRoot),
  colorRoots: fromMap(index.colorRoots),
  spacingRoots: [...index.spacingRoots],
  numericRoots: [...index.numericRoots],
  rootRanks: fromMap(index.rootRanks),
  mediaVariants: fromMap(computeMediaVariants(ds, REM)),
}

const out = join(here, '../src/generated/stock-theme.ts')
mkdirSync(dirname(out), { recursive: true })
writeFileSync(
  out,
  `// AUTO-GENERATED by \`npm run generate\`. Do not edit by hand.\n` +
    `// Regenerate when \`tailwindcss\` is updated.\n` +
    `import type { StockTheme } from '../embedded.ts'\n\n` +
    `export const stockTheme: StockTheme = ${JSON.stringify(data)}\n`,
)

const size = (JSON.stringify(data).length / 1024).toFixed(0)
console.log(
  `Generated stock-theme.ts for tailwindcss@${tailwindVersion}: ` +
    `${Object.keys(plainDecls).length} plain + ${tokenDecls.length} token decls ` +
    `(of ${entries.length}), ${size}KB`,
)
